### ISSUE TITLE
Ansible: Manage Docker Swarm 

### ISSUE THREAD

**Issue by mattstruble** [mattstruble/infra#2]
Add docker support for managing stacks within my swarm containers. 

```yaml 
- hosts: my-swarm-manager-nodes[0]
  tasks:
    - name: deploy services to swarm
      community.general.docker_stack:
        name: "{{ item.name }}"
        state: present
        compose:
          - "{{ item.compose }}"
      with_items: "{{ my_services }}"
      when: my_services is defined
  vars:
    my_services:
      - name: some_stack:
        compose: "{{ lookup('file', '../../docker/some_stack.yml') | from_yaml }}"
```
--- 
Ref: https://old.reddit.com/r/ansible/comments/lb1qvq/ansible_and_docker_stacks/glsisqq/
